Fix compilation error with clang due to incorrect template usage
Use template keyword to disambiguate dependent names in param.h when
using clang compiler:

./ramulator2/src/base/param.h:91:33: error: use 'template' keyword to treat 'as' as a dependent template name
   91 |           return _config[_name].as<T>();
      |                                 ^
      |                                 template

This change ensures compatibility with clang's parsing rules for
dependent names.

Signed-off-by: Yangyu Chen <cyy@cyyself.name>